<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <Version>2.1.0</Version><AssemblyVersion>2.1.0.0</AssemblyVersion><FileVersion>2.1.0.0</FileVersion><Product>R3 M-Kobi</Product><ApplicationIcon>Assets\BarcodePro.ico</ApplicationIcon><ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings><ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.31" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>

</Project>




